FROM fedora

RUN dnf -y update && dnf install -y openssh-server sudo

RUN useradd -m iti && echo "iti:123" | chpasswd

RUN usermod -aG wheel iti

RUN systemctl enable sshd

CMD ["/usr/sbin/sshd", "-D"]
